name: eirsaf
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Per chiamare API HTTP (meteo)
  http: ^1.5.0
  # Per ottenere la posizione del dispositivo
  geolocator: ^14.0.2
  # Per il file JSON
  file_picker: ^10.3.3
  # Per leggere/scrivere file locali
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  share_plus: ^12.0.0
  geocoding: ^2.1.1
  geolocator_web: ^4.1.3
  

flutter_native_splash:
  color: "#3F51B5"                 # colore sfondo (chiaro)
  color_dark: "#2F3A6B"            # colore sfondo (tema scuro)
  image: lib/assets/splash/splash.png       # logo trasparente
  image_dark: lib/assets/splash/splash.png  # logo (tema scuro)
  android_12:
    color: "#3F51B5"
    color_dark: "#2F3A6B"
    image: lib/assets/splash/splash_logo_1152.png
    image_dark: lib/assets/splash/splash_logo_1152.png
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21

  # iOS & fallback
  image_path: lib/assets/launcher/app_icon_safe.png
  remove_alpha_ios: true

  # Android adaptive
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: lib/assets/launcher/app_icon_foreground.png


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true